from .settings import (
    SCREEN, RANK_FILE, 
    BACKGROUND, THISORTHAT,
    COLOR_ROJO, COLOR_AZUL,  COLOR_BLANCO,
    SONIDO_SELECT, SONIDO_MUSIC, SONIDO_MENU, SONIDO_OPCIONES, SONIDO_RANKING,
    BUBBLE_GUMS, BUBBLEBOY, BUBBLE_BOBBLE
)


